# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drink_size',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='user',
            name='required_ounces',
            field=models.FloatField(default=64.0, null=True),
        ),
    ]
