# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0002_auto_20160908_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='required_ounces',
            new_name='ounces_in_a_period',
        ),
    ]
