# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0002_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_id', models.CharField(max_length=9)),
                ('time', models.CharField(max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit.Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit.User')),
            ],
        ),
    ]
