# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0003_auto_20160908_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='drink_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='end_of_period',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ounces_in_a_period',
        ),
        migrations.RemoveField(
            model_name='user',
            name='start_of_period',
        ),
    ]
