# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0004_auto_20160913_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token_expiration',
            field=models.CharField(default='2016-09-15 12:00', max_length=22),
        ),
    ]
