# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0005_user_access_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token_expiration',
            field=models.CharField(default='2016-09-15 12:00+00:00', max_length=22),
        ),
    ]
