# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0010_auto_20160918_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
