# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0011_auto_20160918_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.CharField(max_length=22),
        ),
    ]
