# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0012_auto_20160918_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token_expiration',
            field=models.CharField(default='2090-09-15 12:00+00:00', max_length=22),
        ),
    ]
