# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0013_auto_20160919_1852'),
        ('fitbit', '0013_auto_20160919_1717'),
    ]

    operations = [
    ]
