# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0014_merge_20160919_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
