# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0015_user_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_id', models.IntegerField()),
                ('is_main_sleep', models.IntegerField()),
                ('start_time', models.CharField(max_length=22)),
                ('end_time', models.CharField(max_length=22)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='access_token_expiration',
            field=models.CharField(default='2012-09-15 12:00+00:00', max_length=22),
        ),
        migrations.AddField(
            model_name='sleep',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit.User'),
        ),
    ]
