# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0016_auto_20160929_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_sleep_sync',
            field=models.CharField(default=None, max_length=22),
        ),
    ]
