# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0017_user_last_sleep_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_sleep_sync',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
