# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0018_auto_20160929_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='fitbit_id',
            field=models.CharField(max_length=20),
        ),
    ]
