# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0019_auto_20160929_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(max_length=260, null=True),
        ),
    ]
