# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watervibe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=256)),
                ('app_id', models.IntegerField(default=0)),
                ('start_of_period', models.DateTimeField(null=True)),
                ('end_of_period', models.DateTimeField(null=True)),
                ('ounces_in_a_day', models.FloatField(default=64.0, null=True)),
                ('drink_size', models.FloatField(default=8.0)),
            ],
        ),
    ]
