# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watervibe', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='next_sync_time',
            field=models.DateTimeField(null=True),
        ),
    ]
