# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watervibe', '0004_user_maximum_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watervibe.User'),
        ),
    ]
