# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watervibe', '0005_reminder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.CharField(max_length=22),
        ),
    ]
