# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watervibe', '0006_auto_20160915_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='end_of_period',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='next_sync_time',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_of_period',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
