# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watervibe', '0007_auto_20160915_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='app',
            field=models.CharField(default='fitbit', max_length=256),
        ),
        migrations.AddField(
            model_name='reminder',
            name='app_id',
            field=models.IntegerField(null=True),
        ),
    ]
