# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watervibe', '0008_auto_20160915_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_sync',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_update',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
