# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watervibe', '0009_auto_20160919_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=22)),
                ('end_date', models.CharField(max_length=22)),
                ('tag', models.CharField(max_length=256)),
                ('day_of_week', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('hour', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='times',
            field=models.ManyToManyField(to='watervibe.Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watervibe.User'),
        ),
    ]
