# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watervibe', '0010_auto_20161001_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='beginning_sample_date',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
