# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watervibe', '0011_user_beginning_sample_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='event',
            name='day_of_week',
            field=models.IntegerField(default=0),
        ),
    ]
