# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watervibe', '0012_auto_20161004_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fringe_probability',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fringe_variance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='probability',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='probability_variance',
            field=models.FloatField(null=True),
        ),
    ]
